version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "yearly"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/arktwin/viewer/"
    schedule:
      interval: "yearly"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
    open-pull-requests-limit: 30
