changelog:
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Continuous Integration
      labels:
        - ci
    - title: Dependencies
      labels:
        - dependencies
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
