name: Dependency Submission

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Dependency-Submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: scalacenter/sbt-dependency-submission@v3
      with:
        working-directory: arktwin
