name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write # this permission is needed to submit the dependency graph

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: sbt
        cache-dependency-path: arktwin/build.sbt

    # check before automatic execution at compile time
    - name: sbt scalafmtCheck
      working-directory: arktwin
      run: sbt center/scalafmtCheck center/Test/scalafmtCheck common/scalafmtCheck common/Test/scalafmtCheck e2e/Test/scalafmtCheck edge/scalafmtCheck edge/Test/scalafmtCheck

    # check before automatic execution at compile time
    - name: sbt headerCheck
      working-directory: arktwin
      run: sbt center/headerCheck center/Test/headerCheck common/headerCheck common/Test/headerCheck e2e/Test/headerCheck edge/headerCheck edge/Test/headerCheck

    - name: sbt test
      working-directory: arktwin
      run: sbt test

    - uses: scalacenter/sbt-dependency-submission@v3
      with:
        working-directory: arktwin
