name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write # this permission is needed to submit the dependency graph

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: sbt
        cache-dependency-path: arktwin/build.sbt
    - name: Run tests
      working-directory: arktwin
      run: sbt test
    - name: Test to compile e2e
      working-directory: arktwin
      run: sbt e2e/compile
    - uses: scalacenter/sbt-dependency-submission@v3
      with:
        working-directory: arktwin
